version: 2
jobs:
  build:
    docker:
      - image: node:8.12.0

    steps:
    - checkout

    - run:
        name: NPM 6.4.1
        command: npm install -g npm@6.4.1

    - run:
        name: Install node modules
        command: npm ci

    - run:
        name: Lint
        command: npm run lint

    - run:
        name: Test
        command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
