version: 2
jobs:
  build:
    docker:
      - image: node:10.15.0

    steps:
    - checkout

    - run:
        command: npm ci

    - run:
        command: npm run build

    - run:
        command: npm run lint

    - run:
        name: Install mediainfo
        command: |
          apt-get update
          wget https://mediaarea.net/download/binary/libzen0/0.4.37/libzen0_0.4.37-1_amd64.Debian_8.0.deb
          dpkg -i libzen0_0.4.37-1_amd64.Debian_8.0.deb
          wget https://mediaarea.net/download/binary/libmediainfo0/18.08.1/libmediainfo0_18.08.1-1_amd64.Debian_8.0.deb
          apt install libmms0
          dpkg -i libmediainfo0_18.08.1-1_amd64.Debian_8.0.deb
          wget https://mediaarea.net/download/binary/mediainfo/18.08.1/mediainfo_18.08.1-1_amd64.Debian_8.0.deb
          dpkg -i mediainfo_18.08.1-1_amd64.Debian_8.0.deb

    - run:
        command: npm run test -- --ci --coverage --runInBand --reporters=default --reporters=jest-junit
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

    - run:
        name: Upload coverage to Codacy
        command: cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage

    - run:
        name: Upload coverage to Codecov
        command: bash <(curl -s https://codecov.io/bash)

    - store_test_results:
        path: reports/junit

    - store_artifacts:
        path: reports/junit
